(function () {
  const DATA = {
    INGREDIENTS: [
      { id: "garlic", name: "Garlic", emoji: "🧄", cost: 2, category: "seasoning", tags: ["aroma", "umami"], sweet: 0, salty: 1, sour: 0, bitter: 1, umami: 5, texture: 1, heat: 0, fresh: 4, rarity: 1, asset: "assets/ingredients/garlic.svg", prepAsset: "assets/ingredients/garlic_whole_01.png", prepChoppedAsset: "assets/ingredients/garlic_chopped_01.png", cookAsset: "assets/ingredients/garlic_saute_01.png" },
      { id: "honey", name: "Honey", emoji: "🍯", cost: 3, category: "sauce", tags: ["sweet", "glaze"], sweet: 8, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 2, heat: 0, fresh: 2, rarity: 2, asset: "assets/ingredients/honey.svg" },
      { id: "apple", name: "Apple", emoji: "🍎", cost: 2, category: "fruit", tags: ["fruit", "sweet"], sweet: 5, salty: 0, sour: 3, bitter: 0, umami: 0, texture: 2, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/apple.svg" },
      { id: "berrymix", name: "Berry Mix", emoji: "🫐", cost: 3, category: "fruit", tags: ["berry", "sweet"], sweet: 7, salty: 0, sour: 3, bitter: 0, umami: 0, texture: 2, heat: 0, fresh: 8, rarity: 2, asset: "assets/ingredients/berrymix.svg" },
      { id: "cinnamon", name: "Cinnamon", emoji: "🟤", cost: 2, category: "baking", tags: ["warm", "spice"], sweet: 2, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 0, heat: 1, fresh: 0, rarity: 1, asset: "assets/ingredients/cinnamon.svg" },
      { id: "vanilla", name: "Vanilla", emoji: "🌼", cost: 3, category: "baking", tags: ["sweet", "aroma"], sweet: 4, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 0, heat: 0, fresh: 1, rarity: 2, asset: "assets/ingredients/vanilla.svg" },
      { id: "sugar", name: "Sugar", emoji: "🍬", cost: 2, category: "baking", tags: ["sweet", "bake"], sweet: 9, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 1, heat: 0, fresh: 0, rarity: 1, asset: "assets/ingredients/sugar.svg" },
      { id: "lemon", name: "Lemon", emoji: "🍋", cost: 2, category: "vegetable", tags: ["acid", "fresh"], sweet: 1, salty: 0, sour: 8, bitter: 1, umami: 0, texture: 0, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/lemon.svg" },
      { id: "butter", name: "Butter", emoji: "🧈", cost: 3, category: "dairy", tags: ["rich", "smooth"], sweet: 1, salty: 3, sour: 0, bitter: 0, umami: 4, texture: 6, heat: 0, fresh: 2, rarity: 2, asset: "assets/ingredients/butter_01.png", prepAsset: "assets/ingredients/butter_01.png", cookAsset: "assets/ingredients/butter_melt_01.png" },
      { id: "chili", name: "Chili", emoji: "🌶️", cost: 3, category: "seasoning", tags: ["heat", "risk"], sweet: 0, salty: 0, sour: 0, bitter: 1, umami: 1, texture: 0, heat: 8, fresh: 4, rarity: 2, asset: "assets/ingredients/chili_flakes_01.png", cookAsset: "assets/ingredients/chili_flakes_01.png" },
      { id: "basil", name: "Basil", emoji: "🌿", cost: 2, category: "herb", tags: ["herb", "fresh"], sweet: 1, salty: 0, sour: 0, bitter: 2, umami: 1, texture: 0, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/basil.svg" },
      { id: "tomato", name: "Tomato", emoji: "🍅", cost: 2, category: "vegetable", tags: ["acid", "sauce"], sweet: 3, salty: 0, sour: 4, bitter: 0, umami: 3, texture: 3, heat: 0, fresh: 7, rarity: 1, asset: "assets/ingredients/tomato.svg", prepAsset: "assets/ingredients/tomato_whole_01.png", prepChoppedAsset: "assets/ingredients/tomato_sliced_01.png" },
      { id: "mushroom", name: "Mushroom", emoji: "🍄", cost: 4, category: "vegetable", tags: ["earthy", "umami"], sweet: 0, salty: 0, sour: 0, bitter: 1, umami: 8, texture: 4, heat: 0, fresh: 3, rarity: 3, prepAsset: "assets/ingredients/mushroom_sliced_01.png", prepChoppedAsset: "assets/ingredients/mushroom_sliced_01.png" },
      { id: "cheese", name: "Cheese", emoji: "🧀", cost: 4, category: "dairy", tags: ["rich", "umami"], sweet: 0, salty: 4, sour: 0, bitter: 0, umami: 7, texture: 5, heat: 0, fresh: 1, rarity: 2, asset: "assets/ingredients/cheese.svg" },
      { id: "onion", name: "Onion", emoji: "🧅", cost: 2, category: "vegetable", tags: ["aroma", "savory"], sweet: 3, salty: 1, sour: 0, bitter: 1, umami: 4, texture: 2, heat: 0, fresh: 4, rarity: 1, prepAsset: "assets/ingredients/onion_whole_01.png", prepChoppedAsset: "assets/ingredients/onion_chopped_01.png" },
      { id: "soy", name: "Soy", emoji: "🥢", cost: 3, category: "sauce", tags: ["salty", "umami"], sweet: 0, salty: 7, sour: 0, bitter: 0, umami: 7, texture: 1, heat: 0, fresh: 0, rarity: 2, asset: "assets/ingredients/soy.svg" },
      { id: "ginger", name: "Ginger", emoji: "🫚", cost: 3, category: "seasoning", tags: ["spice", "fresh"], sweet: 1, salty: 0, sour: 2, bitter: 0, umami: 2, texture: 1, heat: 5, fresh: 5, rarity: 2, asset: "assets/ingredients/ginger.svg", prepAsset: "assets/ingredients/ginger.svg" },
      { id: "dill", name: "Dill", emoji: "🌿", cost: 2, category: "herb", tags: ["fresh", "bright"], sweet: 0, salty: 0, sour: 0, bitter: 1, umami: 1, texture: 0, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/dill.svg" },
      { id: "mint", name: "Mint", emoji: "🌱", cost: 2, category: "herb", tags: ["cool", "fresh"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 0, texture: 0, heat: 0, fresh: 9, rarity: 1, asset: "assets/ingredients/mint.svg" },
      { id: "rosemary", name: "Rosemary", emoji: "🌿", cost: 2, category: "herb", tags: ["piney", "roast"], sweet: 0, salty: 0, sour: 0, bitter: 1, umami: 2, texture: 0, heat: 0, fresh: 7, rarity: 1, asset: "assets/ingredients/rosemary.svg" },
      { id: "thyme", name: "Thyme", emoji: "🌿", cost: 2, category: "herb", tags: ["earthy", "roast"], sweet: 0, salty: 0, sour: 0, bitter: 1, umami: 2, texture: 0, heat: 0, fresh: 7, rarity: 1, asset: "assets/ingredients/thyme.svg" },
      { id: "oliveoil", name: "Olive Oil", emoji: "🫒", cost: 3, category: "sauce", tags: ["silky", "finish"], sweet: 0, salty: 0, sour: 0, bitter: 0, umami: 2, texture: 2, heat: 0, fresh: 1, rarity: 2, asset: "assets/props/olive_oil_bottle_01.png", prepAsset: "assets/props/olive_oil_bottle_01.png" },
      { id: "rice", name: "Rice", emoji: "🍚", cost: 2, category: "starch", tags: ["base", "mild"], sweet: 0, salty: 0, sour: 0, bitter: 0, umami: 2, texture: 5, heat: 0, fresh: 1, rarity: 1, asset: "assets/ingredients/rice_cooked_bowl_01.png", prepAsset: "assets/ingredients/rice_cooked_bowl_01.png" },
      { id: "avocado", name: "Avocado", emoji: "🥑", cost: 4, category: "vegetable", tags: ["creamy", "fresh"], sweet: 1, salty: 0, sour: 0, bitter: 0, umami: 3, texture: 6, heat: 0, fresh: 7, rarity: 2, asset: "assets/ingredients/avocado.svg" },
      { id: "truffle", name: "Truffle", emoji: "⚫", cost: 6, category: "luxury", tags: ["luxury", "umami"], sweet: 0, salty: 1, sour: 0, bitter: 0, umami: 10, texture: 2, heat: 0, fresh: 2, rarity: 5, asset: "assets/ingredients/truffle.svg" },
      { id: "chocolate", name: "Chocolate", emoji: "🍫", cost: 5, category: "wild", tags: ["dessert", "wild"], sweet: 9, salty: 0, sour: 0, bitter: 3, umami: 0, texture: 3, heat: 0, fresh: 0, rarity: 4, asset: "assets/ingredients/chocolate.svg" },
      { id: "pineapple", name: "Pineapple", emoji: "🍍", cost: 4, category: "wild", tags: ["tropical", "wild"], sweet: 8, salty: 0, sour: 4, bitter: 0, umami: 1, texture: 3, heat: 0, fresh: 8, rarity: 3, asset: "assets/ingredients/pineapple.svg" },
      { id: "bacon", name: "Bacon", emoji: "🥓", cost: 4, category: "meat", tags: ["smoky", "fat"], sweet: 0, salty: 6, sour: 0, bitter: 0, umami: 8, texture: 5, heat: 0, fresh: 0, rarity: 3, asset: "assets/ingredients/bacon.svg" },
      { id: "shrimp", name: "Shrimp", emoji: "🦐", cost: 4, category: "seafood", tags: ["sea", "fresh"], sweet: 0, salty: 3, sour: 0, bitter: 0, umami: 7, texture: 4, heat: 0, fresh: 6, rarity: 3, asset: "assets/ingredients/shrimp.svg" },
      { id: "egg", name: "Egg", emoji: "🥚", cost: 2, category: "dairy", tags: ["binder", "rich"], sweet: 0, salty: 1, sour: 0, bitter: 0, umami: 4, texture: 5, heat: 0, fresh: 1, rarity: 1, asset: "assets/ingredients/egg.svg" },
      { id: "cilantro", name: "Cilantro", emoji: "🌱", cost: 2, category: "herb", tags: ["herb", "fresh"], sweet: 0, salty: 0, sour: 0, bitter: 1, umami: 1, texture: 0, heat: 0, fresh: 9, rarity: 1, asset: "assets/ingredients/cilantro.svg", prepAsset: "assets/ingredients/cilantro.svg" },
      { id: "pepper", name: "Pepper", emoji: "🫑", cost: 2, category: "vegetable", tags: ["crunch", "fresh"], sweet: 2, salty: 0, sour: 0, bitter: 0, umami: 1, texture: 3, heat: 0, fresh: 7, rarity: 1, prepAsset: "assets/ingredients/bell_pepper_whole_01.png", prepChoppedAsset: "assets/ingredients/bell_pepper_sliced_01.png" },
      { id: "cream", name: "Cream", emoji: "🥛", cost: 3, category: "dairy", tags: ["rich", "smooth"], sweet: 2, salty: 1, sour: 0, bitter: 0, umami: 3, texture: 6, heat: 0, fresh: 0, rarity: 2, asset: "assets/ingredients/cream.svg" },
      { id: "paprika", name: "Paprika", emoji: "🧂", cost: 3, category: "seasoning", tags: ["smoky", "spice"], sweet: 1, salty: 1, sour: 0, bitter: 1, umami: 3, texture: 0, heat: 3, fresh: 1, rarity: 2, asset: "assets/ingredients/paprika.svg" },
      { id: "cajun", name: "Cajun Spice", emoji: "🌶️", cost: 3, category: "seasoning", tags: ["spice", "heat"], sweet: 1, salty: 3, sour: 0, bitter: 1, umami: 2, texture: 0, heat: 7, fresh: 2, rarity: 2, asset: "assets/ingredients/cajun.svg" },
      { id: "blackpepper", name: "Black Pepper", emoji: "⚫", cost: 2, category: "seasoning", tags: ["spice", "sharp"], sweet: 0, salty: 0, sour: 0, bitter: 2, umami: 1, texture: 0, heat: 4, fresh: 0, rarity: 1, asset: "assets/ingredients/blackpepper.svg" },
      { id: "cumin", name: "Cumin", emoji: "🟤", cost: 2, category: "seasoning", tags: ["warm", "earthy"], sweet: 0, salty: 0, sour: 0, bitter: 1, umami: 2, texture: 0, heat: 3, fresh: 0, rarity: 1, asset: "assets/ingredients/cumin.svg" },
      { id: "garlicpowder", name: "Garlic Powder", emoji: "🧂", cost: 2, category: "seasoning", tags: ["garlic", "dry"], sweet: 0, salty: 1, sour: 0, bitter: 1, umami: 4, texture: 0, heat: 0, fresh: 0, rarity: 1, asset: "assets/ingredients/garlicpowder.svg" },
      { id: "chilicrisp", name: "Chili Crisp", emoji: "🌶️", cost: 4, category: "sauce", tags: ["heat", "crunch"], sweet: 1, salty: 2, sour: 0, bitter: 0, umami: 3, texture: 3, heat: 8, fresh: 0, rarity: 3, asset: "assets/ingredients/chilicrisp.svg" },
      { id: "bbq", name: "BBQ Sauce", emoji: "🥫", cost: 4, category: "sauce", tags: ["sweet", "smoky"], sweet: 7, salty: 4, sour: 2, bitter: 0, umami: 4, texture: 3, heat: 1, fresh: 1, rarity: 3, asset: "assets/ingredients/bbq.svg" },
      { id: "hotsauce", name: "Hot Sauce", emoji: "🧴", cost: 3, category: "sauce", tags: ["heat", "acid"], sweet: 1, salty: 2, sour: 4, bitter: 0, umami: 1, texture: 0, heat: 8, fresh: 1, rarity: 2, asset: "assets/ingredients/hotsauce.svg" },
      { id: "teriyaki", name: "Teriyaki", emoji: "🍶", cost: 4, category: "sauce", tags: ["sweet", "umami"], sweet: 5, salty: 5, sour: 1, bitter: 0, umami: 5, texture: 1, heat: 0, fresh: 0, rarity: 3, asset: "assets/ingredients/teriyaki.svg" },
      { id: "sesameoil", name: "Sesame Oil", emoji: "🟤", cost: 3, category: "sauce", tags: ["nutty", "aroma"], sweet: 0, salty: 1, sour: 0, bitter: 0, umami: 4, texture: 2, heat: 0, fresh: 0, rarity: 2, asset: "assets/ingredients/sesameoil.svg" },
      { id: "hoisin", name: "Hoisin", emoji: "🥫", cost: 4, category: "sauce", tags: ["sweet", "glaze"], sweet: 5, salty: 5, sour: 0, bitter: 0, umami: 4, texture: 2, heat: 0, fresh: 0, rarity: 3, asset: "assets/ingredients/hoisin.svg" },
      { id: "pesto", name: "Pesto", emoji: "🌿", cost: 4, category: "sauce", tags: ["herb", "rich"], sweet: 0, salty: 4, sour: 0, bitter: 1, umami: 5, texture: 3, heat: 0, fresh: 5, rarity: 3, asset: "assets/ingredients/pesto.svg" },
      { id: "vinegar", name: "Vinegar", emoji: "🍾", cost: 2, category: "sauce", tags: ["acid", "sharp"], sweet: 0, salty: 0, sour: 8, bitter: 0, umami: 0, texture: 0, heat: 0, fresh: 0, rarity: 1, asset: "assets/ingredients/vinegar.svg" },
      { id: "lime", name: "Lime", emoji: "🟢", cost: 2, category: "vegetable", tags: ["citrus", "bright"], sweet: 1, salty: 0, sour: 7, bitter: 1, umami: 0, texture: 0, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/lime.svg" },
      { id: "scallion", name: "Scallion", emoji: "🧅", cost: 2, category: "vegetable", tags: ["fresh", "sharp"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 2, texture: 1, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/scallion.svg" },
      { id: "chiliflakes", name: "Chili Flakes", emoji: "🌶️", cost: 2, category: "seasoning", tags: ["heat", "finish"], sweet: 0, salty: 1, sour: 0, bitter: 0, umami: 1, texture: 0, heat: 7, fresh: 1, rarity: 1, asset: "assets/ingredients/chiliflakes.svg" },
      { id: "sesame", name: "Sesame Seeds", emoji: "⚪", cost: 2, category: "seasoning", tags: ["nutty", "crunch"], sweet: 0, salty: 1, sour: 0, bitter: 0, umami: 2, texture: 4, heat: 0, fresh: 0, rarity: 1, asset: "assets/ingredients/sesame.svg" },
      { id: "parmesan", name: "Parmesan", emoji: "🧀", cost: 4, category: "dairy", tags: ["salty", "finish"], sweet: 0, salty: 5, sour: 0, bitter: 0, umami: 8, texture: 3, heat: 0, fresh: 0, rarity: 3, asset: "assets/ingredients/parmesan.svg" },
      { id: "mozzarella", name: "Mozzarella", emoji: "🧀", cost: 4, category: "dairy", tags: ["cheese", "stretch"], sweet: 0, salty: 3, sour: 0, bitter: 0, umami: 6, texture: 6, heat: 0, fresh: 1, rarity: 3, asset: "assets/ingredients/mozzarella.svg" },
      { id: "piecrust", name: "Pie Crust", emoji: "🥧", cost: 3, category: "baking", tags: ["bake", "crust"], sweet: 1, salty: 1, sour: 0, bitter: 0, umami: 1, texture: 6, heat: 0, fresh: 0, rarity: 2, asset: "assets/ingredients/piecrust.svg" },
      { id: "whippedcream", name: "Whipped Cream", emoji: "🍦", cost: 3, category: "dairy", tags: ["dessert", "soft"], sweet: 6, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 5, heat: 0, fresh: 1, rarity: 2, asset: "assets/ingredients/whippedcream.svg" },
      { id: "potato", name: "Potato", emoji: "🥔", cost: 2, category: "starch", tags: ["starch", "comfort"], sweet: 1, salty: 0, sour: 0, bitter: 0, umami: 2, texture: 4, heat: 0, fresh: 1, rarity: 1, asset: "assets/ingredients/potato.svg" },
      { id: "broccoli", name: "Broccoli", emoji: "🥦", cost: 2, category: "vegetable", tags: ["green", "fresh"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 2, texture: 3, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/broccoli.svg" },
      { id: "carrot", name: "Carrot", emoji: "🥕", cost: 2, category: "vegetable", tags: ["sweet", "crunch"], sweet: 4, salty: 0, sour: 0, bitter: 0, umami: 1, texture: 3, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/carrot.svg" },
      { id: "corn", name: "Corn", emoji: "🌽", cost: 2, category: "vegetable", tags: ["sweet", "roasted"], sweet: 5, salty: 0, sour: 0, bitter: 0, umami: 1, texture: 3, heat: 0, fresh: 6, rarity: 1, asset: "assets/ingredients/corn.svg" },
      { id: "zucchini", name: "Zucchini", emoji: "🥒", cost: 2, category: "vegetable", tags: ["green", "light"], sweet: 1, salty: 0, sour: 0, bitter: 0, umami: 1, texture: 3, heat: 0, fresh: 7, rarity: 1, asset: "assets/ingredients/zucchini.svg" },
      { id: "asparagus", name: "Asparagus", emoji: "🌱", cost: 3, category: "vegetable", tags: ["green", "fresh"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 2, texture: 3, heat: 0, fresh: 8, rarity: 2, asset: "assets/ingredients/asparagus.svg" },
      { id: "spinach", name: "Spinach", emoji: "🥬", cost: 2, category: "vegetable", tags: ["leafy", "green"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 2, texture: 2, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/spinach.svg" },
      { id: "eggplant", name: "Eggplant", emoji: "🍆", cost: 3, category: "vegetable", tags: ["creamy", "roast"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 4, texture: 4, heat: 0, fresh: 4, rarity: 2, asset: "assets/ingredients/eggplant.svg" },
      { id: "beet", name: "Beet", emoji: "🫜", cost: 3, category: "vegetable", tags: ["earthy", "sweet"], sweet: 4, salty: 0, sour: 0, bitter: 1, umami: 2, texture: 3, heat: 0, fresh: 6, rarity: 2, asset: "assets/ingredients/beet.svg" },
      { id: "cabbage", name: "Cabbage", emoji: "🥬", cost: 2, category: "vegetable", tags: ["crunch", "fresh"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 1, texture: 3, heat: 0, fresh: 7, rarity: 1, asset: "assets/ingredients/cabbage.svg" },
      { id: "pumpkin", name: "Pumpkin", emoji: "🎃", cost: 3, category: "baking", tags: ["bake", "sweet"], sweet: 5, salty: 0, sour: 0, bitter: 0, umami: 1, texture: 4, heat: 0, fresh: 3, rarity: 2, asset: "assets/ingredients/pumpkin.svg" },
      { id: "cherry", name: "Cherry", emoji: "🍒", cost: 3, category: "fruit", tags: ["fruit", "sweet"], sweet: 6, salty: 0, sour: 3, bitter: 0, umami: 0, texture: 2, heat: 0, fresh: 8, rarity: 2, asset: "assets/ingredients/cherry.svg" },
      { id: "peach", name: "Peach", emoji: "🍑", cost: 3, category: "fruit", tags: ["fruit", "juicy"], sweet: 7, salty: 0, sour: 2, bitter: 0, umami: 0, texture: 2, heat: 0, fresh: 8, rarity: 2, asset: "assets/ingredients/peach.svg" },
      { id: "blueberry", name: "Blueberry", emoji: "🫐", cost: 3, category: "fruit", tags: ["berry", "sweet"], sweet: 6, salty: 0, sour: 2, bitter: 0, umami: 0, texture: 2, heat: 0, fresh: 8, rarity: 2, asset: "assets/ingredients/blueberry.svg" },
      { id: "caramel", name: "Caramel", emoji: "🍮", cost: 4, category: "sauce", tags: ["sweet", "sticky"], sweet: 8, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 3, heat: 0, fresh: 0, rarity: 3, asset: "assets/ingredients/caramel.svg" },
      { id: "coconut", name: "Coconut", emoji: "🥥", cost: 3, category: "fruit", tags: ["sweet", "creamy"], sweet: 5, salty: 1, sour: 1, bitter: 0, umami: 0, texture: 3, heat: 0, fresh: 4, rarity: 2, asset: "assets/ingredients/coconut.svg" },
      { id: "custard", name: "Custard", emoji: "🍮", cost: 4, category: "dairy", tags: ["silky", "dessert"], sweet: 4, salty: 1, sour: 0, bitter: 0, umami: 2, texture: 6, heat: 0, fresh: 1, rarity: 3, asset: "assets/ingredients/custard.svg" },
      { id: "grahamcrust", name: "Graham Crust", emoji: "🥧", cost: 3, category: "baking", tags: ["crumb", "bake"], sweet: 3, salty: 1, sour: 0, bitter: 0, umami: 1, texture: 6, heat: 0, fresh: 0, rarity: 2, asset: "assets/ingredients/grahamcrust.svg" },
      { id: "keylime", name: "Key Lime", emoji: "🍈", cost: 3, category: "fruit", tags: ["citrus", "bright"], sweet: 2, salty: 0, sour: 8, bitter: 1, umami: 0, texture: 1, heat: 0, fresh: 9, rarity: 2, asset: "assets/ingredients/keylime.svg" },
      { id: "almond", name: "Almond", emoji: "🌰", cost: 3, category: "wild", tags: ["nutty", "crunch"], sweet: 2, salty: 1, sour: 0, bitter: 1, umami: 2, texture: 5, heat: 0, fresh: 1, rarity: 2, asset: "assets/ingredients/almond.svg" },
      { id: "sprinkles", name: "Sprinkles", emoji: "✨", cost: 2, category: "baking", tags: ["fun", "sweet"], sweet: 6, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 2, heat: 0, fresh: 0, rarity: 1, asset: "assets/ingredients/sprinkles.svg" },
      { id: "powderedsugar", name: "Powdered Sugar", emoji: "❄️", cost: 2, category: "baking", tags: ["finishing", "sweet"], sweet: 7, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 1, heat: 0, fresh: 0, rarity: 1, asset: "assets/ingredients/powderedsugar.svg" },
      { id: "maple", name: "Maple Syrup", emoji: "🍁", cost: 3, category: "sauce", tags: ["sweet", "glaze"], sweet: 8, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 2, heat: 0, fresh: 0, rarity: 2, asset: "assets/ingredients/maple.svg" },
      { id: "miso", name: "Miso", emoji: "🫘", cost: 4, category: "sauce", tags: ["umami", "savory"], sweet: 1, salty: 6, sour: 0, bitter: 0, umami: 9, texture: 2, heat: 0, fresh: 0, rarity: 3, asset: "assets/ingredients/miso.svg" },
      { id: "chilioil", name: "Chili Oil", emoji: "🛢️", cost: 4, category: "sauce", tags: ["heat", "finish"], sweet: 0, salty: 1, sour: 0, bitter: 0, umami: 3, texture: 2, heat: 8, fresh: 0, rarity: 3, asset: "assets/ingredients/chili_oil.svg" },
      { id: "hoisin", name: "Hoisin", emoji: "🥫", cost: 4, category: "sauce", tags: ["sweet", "glaze"], sweet: 5, salty: 5, sour: 0, bitter: 0, umami: 4, texture: 2, heat: 0, fresh: 0, rarity: 3, asset: "assets/ingredients/hoisin.svg" },
      { id: "pesto", name: "Pesto", emoji: "🌿", cost: 4, category: "sauce", tags: ["herb", "rich"], sweet: 0, salty: 4, sour: 0, bitter: 1, umami: 5, texture: 3, heat: 0, fresh: 5, rarity: 3, asset: "assets/ingredients/pesto.svg" },
      { id: "vinegar", name: "Vinegar", emoji: "🍾", cost: 2, category: "sauce", tags: ["acid", "sharp"], sweet: 0, salty: 0, sour: 8, bitter: 0, umami: 0, texture: 0, heat: 0, fresh: 0, rarity: 1, asset: "assets/ingredients/vinegar.svg" },
      { id: "creamcheese", name: "Cream Cheese", emoji: "🧈", cost: 3, category: "dairy", tags: ["smooth", "rich"], sweet: 1, salty: 3, sour: 1, bitter: 0, umami: 4, texture: 6, heat: 0, fresh: 1, rarity: 2, asset: "assets/ingredients/cream_cheese.svg" },
      { id: "yogurt", name: "Yogurt", emoji: "🥛", cost: 2, category: "dairy", tags: ["cool", "tangy"], sweet: 1, salty: 1, sour: 4, bitter: 0, umami: 2, texture: 4, heat: 0, fresh: 5, rarity: 1, asset: "assets/ingredients/yogurt.svg" },
      { id: "ricotta", name: "Ricotta", emoji: "🧀", cost: 3, category: "dairy", tags: ["soft", "rich"], sweet: 1, salty: 2, sour: 1, bitter: 0, umami: 3, texture: 5, heat: 0, fresh: 2, rarity: 2, asset: "assets/ingredients/ricotta.svg" },
      { id: "porkbelly", name: "Pork Belly", emoji: "🥓", cost: 5, category: "meat", tags: ["rich", "crispy"], sweet: 0, salty: 5, sour: 0, bitter: 0, umami: 9, texture: 6, heat: 0, fresh: 0, rarity: 4, asset: "assets/ingredients/porkbelly.svg" },
      { id: "duck", name: "Duck", emoji: "🦆", cost: 5, category: "meat", tags: ["rich", "savory"], sweet: 0, salty: 4, sour: 0, bitter: 0, umami: 9, texture: 6, heat: 0, fresh: 1, rarity: 4, asset: "assets/ingredients/duck.svg" },
      { id: "lamb", name: "Lamb", emoji: "🍖", cost: 5, category: "meat", tags: ["gamey", "bold"], sweet: 0, salty: 3, sour: 0, bitter: 0, umami: 8, texture: 6, heat: 0, fresh: 1, rarity: 4, asset: "assets/ingredients/lamb.svg" },
      { id: "sausage", name: "Sausage", emoji: "🌭", cost: 4, category: "meat", tags: ["smoky", "seasoned"], sweet: 0, salty: 5, sour: 0, bitter: 0, umami: 7, texture: 5, heat: 0, fresh: 0, rarity: 3, asset: "assets/ingredients/sausage.svg" },
      { id: "tuna", name: "Tuna", emoji: "🐟", cost: 5, category: "seafood", tags: ["sea", "clean"], sweet: 1, salty: 3, sour: 0, bitter: 0, umami: 8, texture: 5, heat: 0, fresh: 7, rarity: 4, asset: "assets/ingredients/tuna.svg" },
      { id: "scallop", name: "Scallop", emoji: "🦪", cost: 5, category: "seafood", tags: ["sweet", "delicate"], sweet: 1, salty: 2, sour: 0, bitter: 0, umami: 8, texture: 5, heat: 0, fresh: 7, rarity: 4, asset: "assets/ingredients/scallop.svg" },
      { id: "chickenwing", name: "Chicken Wing", emoji: "🍗", cost: 4, category: "meat", tags: ["crispy", "party"], sweet: 0, salty: 3, sour: 0, bitter: 0, umami: 7, texture: 6, heat: 0, fresh: 1, rarity: 3, asset: "assets/ingredients/chickenstrips.svg" },
      { id: "salmon", name: "Salmon", emoji: "🐟", cost: 5, category: "seafood", tags: ["sea", "luxury"], sweet: 1, salty: 2, sour: 0, bitter: 0, umami: 8, texture: 5, heat: 0, fresh: 6, rarity: 4, asset: "assets/ingredients/salmon.svg" },
      { id: "crab", name: "Crab", emoji: "🦀", cost: 5, category: "seafood", tags: ["sea", "sweet"], sweet: 1, salty: 3, sour: 0, bitter: 0, umami: 8, texture: 4, heat: 0, fresh: 5, rarity: 4, asset: "assets/ingredients/crab.svg" },
      { id: "lobster", name: "Lobster", emoji: "🦞", cost: 6, category: "seafood", tags: ["luxury", "sea"], sweet: 1, salty: 3, sour: 0, bitter: 0, umami: 10, texture: 5, heat: 0, fresh: 5, rarity: 5, asset: "assets/ingredients/lobster.svg" },
      { id: "beefbites", name: "Beef Bites", emoji: "🥩", cost: 4, category: "meat", tags: ["savory", "sear"], sweet: 0, salty: 2, sour: 0, bitter: 0, umami: 8, texture: 5, heat: 0, fresh: 1, rarity: 3, asset: "assets/ingredients/beefbites.svg" },
      { id: "chickenstrips", name: "Chicken Strips", emoji: "🍗", cost: 4, category: "meat", tags: ["crisp", "protein"], sweet: 0, salty: 2, sour: 0, bitter: 0, umami: 7, texture: 6, heat: 0, fresh: 1, rarity: 3, asset: "assets/ingredients/chickenstrips.svg" },
      { id: "oregano", name: "Oregano", emoji: "🌿", cost: 2, category: "herb", tags: ["mediterranean", "earthy"], sweet: 0, salty: 0, sour: 1, bitter: 2, umami: 2, texture: 0, heat: 0, fresh: 5, rarity: 1, asset: "assets/ingredients/oregano.svg" },
      { id: "rosemary", name: "Rosemary", emoji: "🌿", cost: 2, category: "herb", tags: ["pine", "roast"], sweet: 0, salty: 0, sour: 0, bitter: 2, umami: 1, texture: 0, heat: 0, fresh: 6, rarity: 1, asset: "assets/ingredients/rosemary.svg" },
      { id: "mint", name: "Mint", emoji: "🌱", cost: 2, category: "herb", tags: ["fresh", "cool"], sweet: 1, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 0, heat: 0, fresh: 9, rarity: 1, asset: "assets/ingredients/mint.svg" },
      { id: "sage", name: "Sage", emoji: "🌿", cost: 2, category: "herb", tags: ["earthy", "warm"], sweet: 0, salty: 0, sour: 0, bitter: 2, umami: 1, texture: 0, heat: 0, fresh: 5, rarity: 1, asset: "assets/ingredients/sage.svg" },
      { id: "turmeric", name: "Turmeric", emoji: "🟠", cost: 2, category: "seasoning", tags: ["earthy", "bitter"], sweet: 0, salty: 0, sour: 0, bitter: 4, umami: 1, texture: 0, heat: 2, fresh: 0, rarity: 1, asset: "assets/ingredients/turmeric.svg" },
      { id: "curry", name: "Curry Powder", emoji: "🟡", cost: 3, category: "seasoning", tags: ["warm", "spice"], sweet: 1, salty: 1, sour: 0, bitter: 1, umami: 4, texture: 0, heat: 5, fresh: 1, rarity: 2, asset: "assets/ingredients/curry.svg" },
      { id: "nutmeg", name: "Nutmeg", emoji: "🟤", cost: 3, category: "baking", tags: ["warm", "sweet"], sweet: 2, salty: 0, sour: 0, bitter: 1, umami: 0, texture: 0, heat: 0, fresh: 0, rarity: 2, asset: "assets/ingredients/nutmeg.svg" },
      { id: "cardamom", name: "Cardamom", emoji: "🟢", cost: 3, category: "baking", tags: ["floral", "spice"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 0, texture: 0, heat: 0, fresh: 2, rarity: 2, asset: "assets/ingredients/cardamom.svg" },
      { id: "allspice", name: "Allspice", emoji: "🟤", cost: 2, category: "baking", tags: ["warm", "complex"], sweet: 2, salty: 0, sour: 0, bitter: 1, umami: 0, texture: 0, heat: 2, fresh: 0, rarity: 1, asset: "assets/ingredients/allspice.svg" },
      { id: "clove", name: "Clove", emoji: "🟤", cost: 3, category: "baking", tags: ["warm", "pungent"], sweet: 1, salty: 0, sour: 0, bitter: 3, umami: 0, texture: 0, heat: 1, fresh: 0, rarity: 2, asset: "assets/ingredients/clove.svg" },
      { id: "fennel", name: "Fennel Seeds", emoji: "🟢", cost: 2, category: "seasoning", tags: ["licorice", "sweet"], sweet: 2, salty: 0, sour: 0, bitter: 0, umami: 1, texture: 0, heat: 0, fresh: 3, rarity: 1, asset: "assets/ingredients/fennel.svg" },
      { id: "star_anise", name: "Star Anise", emoji: "⭐", cost: 3, category: "seasoning", tags: ["licorice", "warm"], sweet: 1, salty: 0, sour: 0, bitter: 2, umami: 1, texture: 0, heat: 0, fresh: 0, rarity: 2, asset: "assets/ingredients/star_anise.svg" },
      { id: "garam_masala", name: "Garam Masala", emoji: "🟤", cost: 3, category: "seasoning", tags: ["warm", "complex"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 3, texture: 0, heat: 4, fresh: 1, rarity: 2, asset: "assets/ingredients/garam_masala.svg" },
      { id: "zaatar", name: "Za'atar", emoji: "🟢", cost: 3, category: "seasoning", tags: ["herby", "tangy"], sweet: 0, salty: 1, sour: 2, bitter: 1, umami: 2, texture: 1, heat: 1, fresh: 4, rarity: 2, asset: "assets/ingredients/zaatar.svg" },
      { id: "msg", name: "MSG", emoji: "🧂", cost: 1, category: "seasoning", tags: ["umami", "boost"], sweet: 0, salty: 5, sour: 0, bitter: 0, umami: 9, texture: 0, heat: 0, fresh: 0, rarity: 0, asset: "assets/ingredients/msg.svg" },
      { id: "saffron", name: "Saffron", emoji: "🔴", cost: 6, category: "luxury", tags: ["luxury", "floral"], sweet: 0, salty: 0, sour: 0, bitter: 1, umami: 2, texture: 0, heat: 0, fresh: 2, rarity: 5, asset: "assets/ingredients/saffron.svg" },
      { id: "wasabi", name: "Wasabi", emoji: "🟢", cost: 3, category: "seasoning", tags: ["heat", "sharp"], sweet: 0, salty: 1, sour: 0, bitter: 1, umami: 1, texture: 0, heat: 9, fresh: 3, rarity: 2, asset: "assets/ingredients/wasabi.svg" },
      { id: "miso", name: "Miso", emoji: "🟤", cost: 4, category: "sauce", tags: ["umami", "fermented"], sweet: 1, salty: 6, sour: 0, bitter: 0, umami: 9, texture: 2, heat: 0, fresh: 1, rarity: 3, asset: "assets/ingredients/miso.svg" },
      { id: "fish_sauce", name: "Fish Sauce", emoji: "🧴", cost: 3, category: "sauce", tags: ["umami", "fermented"], sweet: 0, salty: 8, sour: 0, bitter: 0, umami: 9, texture: 0, heat: 0, fresh: 0, rarity: 2, asset: "assets/ingredients/fish_sauce.svg" },
      { id: "sriratcha", name: "Sriracha", emoji: "🌶️", cost: 3, category: "sauce", tags: ["heat", "tangy"], sweet: 2, salty: 3, sour: 2, bitter: 0, umami: 2, texture: 1, heat: 7, fresh: 1, rarity: 2, asset: "assets/ingredients/sriratcha.svg" },
      { id: "tahini", name: "Tahini", emoji: "🟤", cost: 4, category: "sauce", tags: ["nutty", "creamy"], sweet: 0, salty: 2, sour: 0, bitter: 1, umami: 3, texture: 5, heat: 0, fresh: 1, rarity: 3, asset: "assets/ingredients/tahini.svg" },
      { id: "eggplant", name: "Eggplant", emoji: "🍆", cost: 2, category: "vegetable", tags: ["earthy", "meaty"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 3, texture: 4, heat: 0, fresh: 5, rarity: 1, asset: "assets/ingredients/eggplant.svg" },
      { id: "kale", name: "Kale", emoji: "🥬", cost: 2, category: "vegetable", tags: ["leafy", "bitter"], sweet: 0, salty: 0, sour: 0, bitter: 3, umami: 1, texture: 3, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/kale.svg" },
      { id: "sweet_potato", name: "Sweet Potato", emoji: "🍠", cost: 2, category: "vegetable", tags: ["sweet", "hearty"], sweet: 5, salty: 0, sour: 0, bitter: 0, umami: 1, texture: 4, heat: 0, fresh: 4, rarity: 1, asset: "assets/ingredients/sweet_potato.svg" },
      { id: "shallot", name: "Shallot", emoji: "🧅", cost: 2, category: "vegetable", tags: ["delicate", "aroma"], sweet: 2, salty: 0, sour: 0, bitter: 1, umami: 3, texture: 1, heat: 0, fresh: 5, rarity: 1, asset: "assets/ingredients/shallot.svg" },
      { id: "celery", name: "Celery", emoji: "🥬", cost: 1, category: "vegetable", tags: ["crunch", "fresh"], sweet: 1, salty: 0, sour: 0, bitter: 1, umami: 1, texture: 4, heat: 0, fresh: 7, rarity: 1, asset: "assets/ingredients/celery.svg" },
      { id: "corn", name: "Corn", emoji: "🌽", cost: 2, category: "vegetable", tags: ["sweet", "crunch"], sweet: 5, salty: 0, sour: 0, bitter: 0, umami: 1, texture: 3, heat: 0, fresh: 4, rarity: 1, asset: "assets/ingredients/corn.svg" },
      { id: "peas", name: "Peas", emoji: "🫛", cost: 2, category: "vegetable", tags: ["sweet", "green"], sweet: 3, salty: 0, sour: 0, bitter: 0, umami: 2, texture: 2, heat: 0, fresh: 6, rarity: 1, asset: "assets/ingredients/peas.svg" },
      { id: "mango", name: "Mango", emoji: "🥭", cost: 3, category: "fruit", tags: ["tropical", "sweet"], sweet: 8, salty: 0, sour: 2, bitter: 0, umami: 0, texture: 3, heat: 0, fresh: 8, rarity: 2, asset: "assets/ingredients/mango.svg" },
      { id: "orange", name: "Orange", emoji: "🍊", cost: 2, category: "fruit", tags: ["citrus", "sweet"], sweet: 5, salty: 0, sour: 4, bitter: 1, umami: 0, texture: 1, heat: 0, fresh: 8, rarity: 1, asset: "assets/ingredients/orange.svg" },
      { id: "strawberry", name: "Strawberry", emoji: "🍓", cost: 3, category: "fruit", tags: ["berry", "sweet"], sweet: 7, salty: 0, sour: 2, bitter: 0, umami: 0, texture: 2, heat: 0, fresh: 8, rarity: 2, asset: "assets/ingredients/strawberry.svg" },
      { id: "banana", name: "Banana", emoji: "🍌", cost: 2, category: "fruit", tags: ["sweet", "creamy"], sweet: 7, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 4, heat: 0, fresh: 3, rarity: 1, asset: "assets/ingredients/banana.svg" },
      { id: "coconut", name: "Coconut", emoji: "🥥", cost: 3, category: "fruit", tags: ["tropical", "creamy"], sweet: 3, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 5, heat: 0, fresh: 4, rarity: 2, asset: "assets/ingredients/coconut.svg" },
      { id: "pomegranate", name: "Pomegranate", emoji: "🔴", cost: 4, category: "fruit", tags: ["tart", "jewel"], sweet: 4, salty: 0, sour: 4, bitter: 1, umami: 0, texture: 2, heat: 0, fresh: 6, rarity: 3, asset: "assets/ingredients/pomegranate.svg" },
      { id: "fig", name: "Fig", emoji: "🟣", cost: 4, category: "fruit", tags: ["sweet", "earthy"], sweet: 6, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 3, heat: 0, fresh: 3, rarity: 3, asset: "assets/ingredients/fig.svg" },
      { id: "date", name: "Date", emoji: "🟤", cost: 3, category: "fruit", tags: ["sweet", "sticky"], sweet: 9, salty: 0, sour: 0, bitter: 0, umami: 0, texture: 3, heat: 0, fresh: 2, rarity: 2, asset: "assets/ingredients/date.svg" },
      { id: "duck", name: "Duck", emoji: "🦆", cost: 5, category: "meat", tags: ["rich", "crispy"], sweet: 1, salty: 2, sour: 0, bitter: 0, umami: 8, texture: 5, heat: 0, fresh: 2, rarity: 4, asset: "assets/ingredients/duck.svg" },
      { id: "lamb", name: "Lamb", emoji: "🐑", cost: 5, category: "meat", tags: ["gamey", "rich"], sweet: 0, salty: 2, sour: 0, bitter: 0, umami: 8, texture: 6, heat: 0, fresh: 2, rarity: 4, asset: "assets/ingredients/lamb.svg" },
      { id: "pork", name: "Pork", emoji: "🐷", cost: 4, category: "meat", tags: ["savory", "fatty"], sweet: 1, salty: 2, sour: 0, bitter: 0, umami: 7, texture: 5, heat: 0, fresh: 1, rarity: 3, asset: "assets/ingredients/pork.svg" },
      { id: "octopus", name: "Octopus", emoji: "🐙", cost: 5, category: "seafood", tags: ["sea", "chewy"], sweet: 0, salty: 3, sour: 0, bitter: 0, umami: 7, texture: 6, heat: 0, fresh: 5, rarity: 4, asset: "assets/ingredients/octopus.svg" },
      { id: "anchovy", name: "Anchovy", emoji: "🐟", cost: 3, category: "seafood", tags: ["salty", "umami"], sweet: 0, salty: 8, sour: 0, bitter: 0, umami: 8, texture: 2, heat: 0, fresh: 2, rarity: 2, asset: "assets/ingredients/anchovy.svg" },
      { id: "goat_cheese", name: "Goat Cheese", emoji: "🧀", cost: 4, category: "dairy", tags: ["tangy", "creamy"], sweet: 0, salty: 3, sour: 3, bitter: 0, umami: 4, texture: 4, heat: 0, fresh: 3, rarity: 3, asset: "assets/ingredients/goat_cheese.svg" },
      { id: "ricotta", name: "Ricotta", emoji: "🧀", cost: 3, category: "dairy", tags: ["creamy", "mild"], sweet: 1, salty: 1, sour: 0, bitter: 0, umami: 2, texture: 5, heat: 0, fresh: 3, rarity: 2, asset: "assets/ingredients/ricotta.svg" },
      { id: "creme_fraiche", name: "Creme Fraiche", emoji: "🥛", cost: 3, category: "dairy", tags: ["rich", "tangy"], sweet: 1, salty: 1, sour: 3, bitter: 0, umami: 2, texture: 5, heat: 0, fresh: 2, rarity: 2, asset: "assets/ingredients/creme_fraiche.svg" },
      { id: "lentils", name: "Lentils", emoji: "🟤", cost: 2, category: "wild", tags: ["hearty", "earthy"], sweet: 0, salty: 0, sour: 0, bitter: 0, umami: 3, texture: 4, heat: 0, fresh: 1, rarity: 1, asset: "assets/ingredients/lentils.svg" },
      { id: "quinoa", name: "Quinoa", emoji: "🌾", cost: 3, category: "wild", tags: ["nutty", "protein"], sweet: 0, salty: 0, sour: 0, bitter: 0, umami: 1, texture: 3, heat: 0, fresh: 1, rarity: 2, asset: "assets/ingredients/quinoa.svg" },
      { id: "couscous", name: "Couscous", emoji: "🌾", cost: 2, category: "wild", tags: ["light", "fluffy"], sweet: 0, salty: 0, sour: 0, bitter: 0, umami: 1, texture: 3, heat: 0, fresh: 1, rarity: 1, asset: "assets/ingredients/couscous.svg" },
    ],
    BASES: [
      { id: "chicken", name: "Chicken", emoji: "🍗", budget: 16, likes: ["garlic", "honey", "lemon", "butter", "chili", "basil", "onion", "pepper", "paprika", "bbq", "oliveoil", "cilantro", "chickenwing", "sausage", "zucchini", "asparagus", "rosemary", "thyme", "garlicpowder", "chilicrisp", "sage", "oregano", "miso", "curry", "mango", "orange", "corn", "sweet_potato"], hates: ["chocolate"], type: "protein", sweet: 0, salty: 1, sour: 0, bitter: 0, umami: 7, texture: 5, heat: 0, fresh: 3, asset: "assets/ingredients/chicken.svg", prepAsset: "assets/ingredients/chicken_breast_raw_01.png" },
      { id: "steak", name: "Steak", emoji: "🥩", budget: 17, likes: ["mushroom", "butter", "garlic", "pepper", "truffle", "onion", "bbq", "potato", "oliveoil", "parmesan", "porkbelly", "blackpepper", "rosemary", "thyme", "sage", "fennel", "goat_cheese", "anchovy", "fig", "date"], hates: ["pineapple", "chocolate"], type: "protein", sweet: 0, salty: 2, sour: 0, bitter: 0, umami: 9, texture: 7, heat: 0, fresh: 2, asset: "assets/ingredients/steak.svg", prepAsset: "assets/ingredients/steak_raw_01.png" },
      { id: "fish", name: "Fish", emoji: "🐟", budget: 16, likes: ["lemon", "basil", "cilantro", "ginger", "garlic", "butter", "oliveoil", "avocado", "shrimp", "salmon", "tuna", "scallop", "dill", "mint", "vinegar"], hates: ["chocolate", "bacon"], type: "seafood", sweet: 1, salty: 2, sour: 0, bitter: 0, umami: 6, texture: 4, heat: 0, fresh: 6, asset: "assets/ingredients/fish.svg" },
      { id: "tofu", name: "Tofu", emoji: "⬜", budget: 16, likes: ["soy", "ginger", "chili", "garlic", "mushroom", "cilantro", "rice", "broccoli", "cajun", "miso", "chilioil", "cabbage", "spinach", "zucchini", "pesto"], hates: ["chocolate"], type: "vegetarian", sweet: 0, salty: 0, sour: 0, bitter: 0, umami: 3, texture: 4, heat: 0, fresh: 4, asset: "assets/ingredients/tofu.svg" },
      { id: "pasta", name: "Pasta", emoji: "🍝", budget: 17, likes: ["tomato", "basil", "cheese", "garlic", "butter", "mushroom", "pepper", "cream", "mozzarella", "oliveoil", "parmesan", "creamcheese", "maple", "pesto", "spinach", "ricotta"], hates: ["pineapple", "chocolate"], type: "carb", sweet: 1, salty: 1, sour: 0, bitter: 0, umami: 4, texture: 6, heat: 0, fresh: 2, asset: "assets/ingredients/pasta.svg", prepAsset: "assets/ingredients/noodles_cooked_bowl_01.png" },
      { id: "ricebowl", name: "Rice Bowl", emoji: "🍚", budget: 15, likes: ["soy", "ginger", "egg", "shrimp", "cilantro", "chili", "broccoli", "teriyaki", "oliveoil", "scallion", "tuna", "chilioil", "cumin", "cabbage", "blackpepper"], hates: ["chocolate"], type: "carb", sweet: 0, salty: 1, sour: 0, bitter: 0, umami: 4, texture: 5, heat: 0, fresh: 2, asset: "assets/ingredients/ricebowl.svg", prepAsset: "assets/ingredients/rice_cooked_bowl_01.png" },
      { id: "burger", name: "Burger", emoji: "🍔", budget: 17, likes: ["cheese", "bacon", "onion", "pepper", "bbq", "potato", "egg", "hotsauce", "sausage", "porkbelly", "hoisin", "blackpepper"], hates: ["lemon", "chocolate"], type: "street", sweet: 0, salty: 2, sour: 0, bitter: 0, umami: 8, texture: 7, heat: 0, fresh: 2, asset: "assets/ingredients/burger.svg" },
      { id: "dessert", name: "Dessert Plate", emoji: "🍰", budget: 16, likes: ["honey", "chocolate", "pineapple", "cream", "butter", "avocado", "apple", "berrymix", "cinnamon", "vanilla", "cherry", "peach", "maple", "pumpkin", "blueberry", "ricotta", "yogurt", "mint", "caramel", "coconut", "custard", "sprinkles", "powderedsugar", "keylime", "almond"], hates: ["bacon", "soy"], type: "sweet", sweet: 8, salty: 1, sour: 0, bitter: 0, umami: 1, texture: 4, heat: 0, fresh: 1, asset: "assets/ingredients/dessert.svg" },
      { id: "pie", name: "Pie", emoji: "🥧", budget: 16, likes: ["apple", "berrymix", "cinnamon", "vanilla", "sugar", "butter", "cream", "piecrust", "lemon", "chocolate", "cherry", "peach", "pumpkin", "maple", "blueberry", "ricotta", "yogurt", "caramel", "coconut", "custard", "grahamcrust", "keylime", "almond", "sprinkles", "powderedsugar"], hates: ["bacon", "soy", "chili"], type: "sweet", sweet: 9, salty: 0, sour: 2, bitter: 0, umami: 0, texture: 5, heat: 0, fresh: 2, asset: "assets/ingredients/pie.svg" }
    ],
    METHODS: [
      { id: "grill", name: "Grill Marks", emoji: "♨️", desc: "Boosts smoky texture and heat.", mod: { texture: 2, umami: 1, fresh: -1, heat: 1 }, likes: ["steak", "burger", "chicken"] },
      { id: "saute", name: "Sauté Flip", emoji: "🍳", desc: "Balanced technique. Safe and clean.", mod: { umami: 1, texture: 1, fresh: 1 }, likes: ["pasta", "fish", "tofu"] },
      { id: "fry", name: "Crispy Fry", emoji: "🍟", desc: "Big crunch, lower freshness.", mod: { texture: 4, salty: 1, fresh: -2 }, likes: ["chicken", "ricebowl", "burger"] },
      { id: "braise", name: "Slow Braise", emoji: "🥘", desc: "Deep flavor, softer texture.", mod: { umami: 3, texture: -1, fresh: -1 }, likes: ["steak", "chicken"] },
      { id: "steam", name: "Clean Steam", emoji: "♨️", desc: "Fresh and light, weaker flavor.", mod: { fresh: 3, umami: -1, texture: -1 }, likes: ["fish", "tofu", "ricebowl"] },
      { id: "smoke", name: "Smoke Show", emoji: "💨", desc: "High-risk, high-flavor.", mod: { umami: 2, bitter: 1, texture: 1, fresh: -2 }, likes: ["steak", "burger", "chicken"] },
      { id: "bake", name: "Bake", emoji: "🥧", desc: "Warm dessert finish. Great for pies.", mod: { sweet: 2, fresh: -1, texture: 2 }, likes: ["pie", "dessert"] }
    ],
    PLATES: {
      street: { name: "Street Food Energy", mult: { creativity: 1.12, presentation: 0.92 }, comment: "street-food swagger" },
      fine: { name: "Fine Dining Flex", mult: { creativity: 0.95, presentation: 1.18 }, comment: "fine-dining polish" },
      comfort: { name: "Comfort Classic", mult: { creativity: 0.9, presentation: 1.0, flavor: 1.08 }, comment: "comfort-food heart" },
      fusion: { name: "Fusion Experiment", mult: { creativity: 1.22, presentation: 0.98 }, comment: "fusion risk" }
    },
    COMBOS: [
      { ids: ["chicken", "honey", "garlic"], points: 18, label: "Honey-garlic magic" },
      { ids: ["chicken", "lemon", "basil"], points: 14, label: "Bright herb chicken" },
      { ids: ["steak", "mushroom", "butter"], points: 18, label: "Steakhouse combo" },
      { ids: ["steak", "truffle", "mushroom"], points: 20, label: "Luxury umami bomb" },
      { ids: ["fish", "lemon", "basil"], points: 18, label: "Clean seafood finish" },
      { ids: ["fish", "ginger", "soy"], points: 15, label: "Asian-style seafood balance" },
      { ids: ["tofu", "soy", "ginger"], points: 18, label: "Tofu flavor foundation" },
      { ids: ["pasta", "tomato", "basil"], points: 18, label: "Italian classic" },
      { ids: ["ricebowl", "soy", "egg"], points: 16, label: "Rice bowl staple" },
      { ids: ["burger", "cheese", "bacon"], points: 18, label: "Loaded burger hit" },
      { ids: ["dessert", "honey", "cream"], points: 15, label: "Dessert satin finish" },
      { ids: ["dessert", "caramel", "coconut"], points: 18, label: "Caramel coconut dream" },
      { ids: ["dessert", "custard", "sprinkles"], points: 17, label: "Custard carnival" },
      { ids: ["dessert", "grahamcrust", "whippedcream"], points: 18, label: "No-bake crowd pleaser" },
      { ids: ["pie", "apple", "cinnamon"], points: 20, label: "Apple pie classic" },
      { ids: ["pie", "berrymix", "vanilla"], points: 18, label: "Berry vanilla pie" },
      { ids: ["pie", "piecrust", "whippedcream"], points: 17, label: "Pie a la mode" },
      { ids: ["pie", "keylime", "custard"], points: 19, label: "Key lime pie crest" },
      { ids: ["pie", "blueberry", "almond"], points: 18, label: "Blueberry almond pie" },
      { ids: ["pie", "apple", "caramel"], points: 17, label: "Caramel apple pie" },
      { ids: ["pie", "cherry", "whippedcream"], points: 18, label: "Cherry pie crown" },
      { ids: ["pie", "peach", "maple"], points: 17, label: "Peach maple pie" },
      { ids: ["pie", "pumpkin", "creamcheese"], points: 19, label: "Pumpkin cream pie" },
      { ids: ["burger", "sausage", "bbq"], points: 16, label: "Backyard loaded burger" },
      { ids: ["chicken", "porkbelly", "bbq"], points: 19, label: "BBQ barn burner" },
      { ids: ["steak", "duck", "miso"], points: 18, label: "Luxury surf-and-turf" },
      { ids: ["fish", "tuna", "lime"], points: 16, label: "Double fish citrus plate" },
      { ids: ["scallop", "chilioil", "lime"], points: 15, label: "Spicy seafood shine" },
      { ids: ["tofu", "miso", "scallion"], points: 17, label: "Miso tofu depth" },
      { ids: ["pasta", "creamcheese", "parmesan"], points: 18, label: "Ultra creamy pasta" },
      { ids: ["ricebowl", "chilioil", "tuna"], points: 17, label: "Spicy tuna bowl" },
      { ids: ["pasta", "pesto", "parmesan"], points: 18, label: "Pesto crown pasta" },
      { ids: ["chicken", "rosemary", "garlic"], points: 17, label: "Rosemary roast chicken" },
      { ids: ["steak", "blackpepper", "butter"], points: 17, label: "Pepper butter steak" },
      { ids: ["fish", "dill", "lemon"], points: 16, label: "Dill lemon fish" },
      { ids: ["burger", "hoisin", "scallion"], points: 15, label: "Hoisin burger stack" },
      { ids: ["tofu", "cabbage", "sesameoil"], points: 16, label: "Sesame cabbage tofu" },
      { ids: ["ricebowl", "cumin", "chicken"], points: 15, label: "Cumin rice bowl" },
      { ids: ["dessert", "blueberry", "ricotta"], points: 17, label: "Blueberry ricotta dessert" },
      { ids: ["dessert", "cherry", "maple"], points: 16, label: "Cherry maple dessert" },
      { ids: ["dessert", "peach", "creamcheese"], points: 17, label: "Peach cheesecake plate" },
      { ids: ["chicken", "sausage", "chilioil"], points: 16, label: "Heatline chicken sausage" },
      { ids: ["dessert", "piecrust", "whippedcream"], points: 16, label: "Dessert pie finish" },
      { ids: ["apple", "cinnamon", "butter"], points: 14, label: "Warm apple filling" },
      { ids: ["berrymix", "whippedcream", "vanilla"], points: 15, label: "Berry cloud dessert" },
      { ids: ["pasta", "cream", "mozzarella"], points: 16, label: "Creamy cheese pasta" },
      { ids: ["fish", "lime", "cilantro"], points: 17, label: "Zesty coastal finish" },
      { ids: ["ricebowl", "sesameoil", "scallion"], points: 15, label: "Wok glossy bowl" },
      { ids: ["chicken", "sesame", "sesameoil"], points: 14, label: "Nutty roast chicken" },
      { ids: ["steak", "parmesan", "mushroom"], points: 17, label: "Steak and parm crust" },
      { ids: ["burger", "chiliflakes", "bbq"], points: 14, label: "Firehouse burger" },
      { ids: ["chicken", "butter", "pepper"], points: 16, label: "Butter-pepper chicken" },
      { ids: ["steak", "butter", "mushroom"], points: 20, label: "Butter mushroom steak" },
      { ids: ["pasta", "oliveoil", "parmesan"], points: 16, label: "Glossy parm pasta" },
      { ids: ["fish", "oliveoil", "lemon"], points: 16, label: "Bright fish finish" },
      { ids: ["shrimp", "garlic", "butter"], points: 18, label: "Garlic butter shrimp" },
      { ids: ["ricebowl", "oliveoil", "scallion"], points: 14, label: "Simple glossy bowl" },
      { ids: ["tofu", "oliveoil", "scallion"], points: 14, label: "Silky tofu finish" }

      { ids: ["mint", "lamb"], label: "Mint Lamb", points: 20, tags: ["classic"] },
      { ids: ["rosemary", "lamb"], label: "Rosemary Lamb", points: 18, tags: ["roast"] },
      { ids: ["sage", "pork"], label: "Sage & Pork", points: 18, tags: ["roast"] },
      { ids: ["curry", "coconut"], label: "Coconut Curry", points: 22, tags: ["tropical"] },
      { ids: ["garam_masala", "yogurt"], label: "Tikka Base", points: 20, tags: ["indian"] },
      { ids: ["miso", "tofu"], label: "Miso Tofu", points: 18, tags: ["umami"] },
      { ids: ["fish_sauce", "lime"], label: "Nam Pla", points: 16, tags: ["thai"] },
      { ids: ["sriratcha", "honey"], label: "Bang Bang", points: 20, tags: ["spicy"] },
      { ids: ["orange", "duck"], label: "Orange Duck", points: 22, tags: ["classic"] },
      { ids: ["mango", "chili"], label: "Mango Heat", points: 18, tags: ["tropical"] },
      { ids: ["fennel", "sausage"], label: "Fennel Sausage", points: 16, tags: ["italian"] },
      { ids: ["pomegranate", "goat_cheese"], label: "Pomegranate Goat Cheese", points: 20, tags: ["salad"] },
      { ids: ["fig", "goat_cheese"], label: "Fig & Goat Cheese", points: 20, tags: ["appetizer"] },
      { ids: ["date", "bacon"], label: "Devils on Horseback", points: 18, tags: ["appetizer"] },
      { ids: ["tahini", "garlic"], label: "Tahini Sauce", points: 14, tags: ["middle eastern"] },
      { ids: ["zaatar", "oliveoil"], label: "Zatar Oil", points: 14, tags: ["middle eastern"] },
      { ids: ["cardamom", "coffee"], label: "Cardamom Coffee", points: 14, tags: ["beverage"] },
      { ids: ["star_anise", "pork"], label: "Five-Spice Pork", points: 20, tags: ["asian"] },
      { ids: ["eggplant", "miso"], label: "Miso Eggplant", points: 18, tags: ["japanese"] },
      { ids: ["corn", "butter"], label: "Corn Butter", points: 12, tags: ["side"] },
      { ids: ["peas", "mint"], label: "Mint Peas", points: 14, tags: ["side"] },
      { ids: ["saffron", "ricebowl"], label: "Saffron Rice", points: 22, tags: ["luxury"] },
      { ids: ["wasabi", "soy"], label: "Wasabi Soy", points: 14, tags: ["japanese"] },
      { ids: ["shallot", "vinegar"], label: "Shallot Vinaigrette", points: 12, tags: ["dressing"] },
      { ids: ["sweet_potato", "marshmallow"], label: "Candied Yam", points: 16, tags: ["sweet"] },
      { ids: ["msg", "garlic"], label: "Umami Bomb", points: 14, tags: ["umami"] },
      { ids: ["anchovy", "garlic"], label: "Anchovy Garlic", points: 14, tags: ["umami"] },
      { ids: ["creme_fraiche", "salmon"], label: "Creme Salmon", points: 18, tags: ["rich"] },
      { ids: ["ricotta", "honey"], label: "Ricotta Honey", points: 14, tags: ["sweet"] },
      { ids: ["lentils", "bacon"], label: "Lentils & Bacon", points: 16, tags: ["hearty"] },
      { ids: ["couscous", "mint"], label: "Mint Couscous", points: 12, tags: ["mediterranean"] },
    ],
    BAD_COMBOS: [
      { ids: ["fish", "chocolate"], points: -24, label: "fish and chocolate disaster" },
      { ids: ["steak", "chocolate"], points: -18, label: "steak dessert confusion" },
      { ids: ["pasta", "pineapple"], points: -12, label: "pasta got too tropical" },
      { ids: ["burger", "lemon"], points: -10, label: "burger got sour for no reason" },
      { ids: ["fish", "bacon"], points: -10, label: "seafood got overpowered" },
      { ids: ["chocolate", "soy"], points: -12, label: "salted chocolate confusion" },
      { ids: ["dessert", "bacon"], points: -18, label: "dessert met the grill" },
      { ids: ["lobster", "bbq"], points: -14, label: "lobster got too casual" },
      { ids: ["pie", "bbq"], points: -16, label: "pie took a smoke break" },
      { ids: ["pie", "miso"], points: -10, label: "pie got too savory" },
      { ids: ["dessert", "chilioil"], points: -16, label: "dessert got hit with heat" },
      { ids: ["fish", "maple"], points: -10, label: "fish got sticky" },
      { ids: ["duck", "chocolate"], points: -14, label: "duck dessert confusion" },
      { ids: ["sausage", "vanilla"], points: -16, label: "sausage met dessert" },
      { ids: ["pesto", "chocolate"], points: -14, label: "pesto lost the plot" },
      { ids: ["hoisin", "pie"], points: -14, label: "pie got a glaze it never asked for" },
      { ids: ["vinegar", "dessert"], points: -12, label: "dessert got too sharp" },
      { ids: ["cabbage", "chocolate"], points: -12, label: "cabbage dessert confusion" },
      { ids: ["mint", "bacon"], points: -10, label: "mint and bacon argument" },
      { ids: ["caramel", "fish"], points: -12, label: "caramel and fish collided" },
      { ids: ["coconut", "bacon"], points: -12, label: "coconut met the grill" },
      { ids: ["custard", "garlic"], points: -14, label: "custard took a wrong turn" },
      { ids: ["grahamcrust", "soy"], points: -10, label: "graham crust went savory" },
      { ids: ["powderedsugar", "chili"], points: -10, label: "powdered sugar got ambushed" },
      { ids: ["pie", "bacon"], points: -18, label: "pie met the grill" },
      { ids: ["pie", "soy"], points: -14, label: "pie got a salty detour" },
      { ids: ["pie", "chili"], points: -16, label: "pie turned into a dare" }
    ],
    REACTIONS: {
      opener: [
        "The crowd leans in as the pan starts to hiss.",
        "The judges are already judging the aroma.",
        "Camera on. Fire on. Nerves on."
      ],
      excellent: [
        "That plate hit the table like a championship belt.",
        "The kitchen just went quiet. That means respect.",
        "Clean finish, loud flavor, serious confidence."
      ],
      strong: [
        "Solid cook. The judges are nodding.",
        "That one has real restaurant energy.",
        "Good balance. Good heat. Good nerves."
      ],
      shaky: [
        "The technique is wobbling, but the idea is still alive.",
        "That plate needs more control to win the room.",
        "The judges can taste the pressure."
      ],
      disaster: [
        "The kitchen winced. That was a rough landing.",
        "Chaos plate. The flavor story got lost in the smoke.",
        "The judges are reaching for water."
      ],
      close: [
        "This one came down to one clean move.",
        "A razor-thin margin. Tiny details decided it.",
        "The scoreboard barely separated them."
      ],
      win: [
        "Winner’s circle energy.",
        "That is a trophy-level plate.",
        "The crowd came to see a chef and got a star."
      ],
      lose: [
        "Close, but the other plate had the sharper finish.",
        "A brave attempt, but the rival read the room better.",
        "The concept was there. The polish was not."
      ],
      tie: [
        "Dead heat. Both chefs survived the heat lamp.",
        "No winner on taste alone. The judges are divided.",
        "A true stalemate in the kitchen arena."
      ]
    },
    CATEGORY_INFO: [
      { id: "all", label: "All" },
      { id: "meat", label: "Meats" },
      { id: "seafood", label: "Seafood" },
      { id: "seasoning", label: "Seasonings" },
      { id: "sauce", label: "Sauces" },
      { id: "vegetable", label: "Veggies" },
      { id: "fruit", label: "Fruit" },
      { id: "herb", label: "Herbs" },
      { id: "dairy", label: "Dairy" },
      { id: "starch", label: "Starches" },
      { id: "baking", label: "Baking" },
      { id: "luxury", label: "Luxury" },
      { id: "wild", label: "Wild Cards" }
    ],
    DEFAULT_CATEGORIES: {
      garlic: "seasoning",
      honey: "sauce",
      lemon: "vegetable",
      butter: "dairy",
      chili: "seasoning",
      basil: "herb",
      tomato: "vegetable",
      mushroom: "vegetable",
      cheese: "dairy",
      onion: "vegetable",
      soy: "sauce",
      ginger: "seasoning",
      apple: "fruit",
      berrymix: "fruit",
      cherry: "fruit",
      peach: "fruit",
      pumpkin: "baking",
      maple: "sauce",
      miso: "sauce",
      chilioil: "sauce",
      pesto: "sauce",
      hoisin: "sauce",
      vinegar: "sauce",
      chilicrisp: "sauce",
      creamcheese: "dairy",
      yogurt: "dairy",
      ricotta: "dairy",
      cinnamon: "baking",
      vanilla: "baking",
      blackpepper: "seasoning",
      cumin: "seasoning",
      garlicpowder: "seasoning",
      sugar: "baking",
      rice: "starch",
      avocado: "vegetable",
      truffle: "luxury",
      chocolate: "wild",
      pineapple: "wild",
      bacon: "meat",
      shrimp: "seafood",
      egg: "dairy",
      cilantro: "herb",
      pepper: "vegetable",
      cream: "dairy",
      paprika: "seasoning",
      cajun: "seasoning",
      bbq: "sauce",
      hotsauce: "sauce",
      teriyaki: "sauce",
      sesameoil: "sauce",
      oliveoil: "sauce",
      lime: "vegetable",
      scallion: "vegetable",
      zucchini: "vegetable",
      asparagus: "vegetable",
      spinach: "vegetable",
      eggplant: "vegetable",
      beet: "vegetable",
      cabbage: "vegetable",
      dill: "herb",
      mint: "herb",
      rosemary: "herb",
      thyme: "herb",
      chiliflakes: "seasoning",
      sesame: "seasoning",
      parmesan: "dairy",
      mozzarella: "dairy",
      piecrust: "baking",
      whippedcream: "dairy",
      caramel: "sauce",
      coconut: "fruit",
      custard: "dairy",
      grahamcrust: "baking",
      keylime: "fruit",
      almond: "wild",
      sprinkles: "baking",
      powderedsugar: "baking",
      potato: "starch",
      broccoli: "vegetable",
      carrot: "vegetable",
      corn: "vegetable",
      salmon: "seafood",
      crab: "seafood",
      lobster: "seafood",
      blueberry: "fruit",
      beefbites: "meat",
      chickenstrips: "meat",
      porkbelly: "meat",
      duck: "meat",
      lamb: "meat",
      sausage: "meat",
      chickenwing: "meat",
      tuna: "seafood",
      scallop: "seafood",
      pie: "dessert"
    },
    CAREER_OPPONENTS: [
      { id: "smoke_king", name: "Chef Smoke King", region: "Austin Smoke Pit", emoji: "🔥", hat: "🤠", colors: ["#7c2d12", "#f59e0b"], rank: "Street Grill Boss", difficulty: "easy", style: "BBQ, smoked meat, bold sauce", base: "burger", method: "smoke", plate: "street", likes: ["bbq", "bacon", "paprika", "potato"], signature: "Smokehouse Burger Stack", lore: "A backyard legend with championship smoke rings and loud crowd energy.", x: 18, y: 36 },
      { id: "mama_marina", name: "Mama Marina", region: "Naples Pasta House", emoji: "🍝", hat: "👵", colors: ["#991b1b", "#f97316"], rank: "Sauce Queen", difficulty: "normal", style: "Pasta, tomato, basil, cheese", base: "pasta", method: "saute", plate: "comfort", likes: ["tomato", "basil", "cheese", "cream", "mozzarella"], signature: "Volcano Pasta Bowl", lore: "Old-school sauce boss. If your seasoning is lazy, she knows instantly.", x: 38, y: 56 },
      { id: "sakura_blade", name: "Chef Sakura Blade", region: "Tokyo Precision Kitchen", emoji: "🍣", hat: "🎌", colors: ["#be123c", "#fbcfe8"], rank: "Knife Master", difficulty: "normal", style: "Seafood, clean cuts, perfect timing", base: "fish", method: "steam", plate: "fine", likes: ["lemon", "cilantro", "shrimp", "salmon"], signature: "Moonlit Sashimi Plate", lore: "Every motion is measured. She wins by being one slice cleaner than everyone else.", x: 58, y: 38 },
      { id: "chef_monsoon", name: "Chef Monsoon", region: "Mumbai Heat Line", emoji: "🌶️", hat: "🧢", colors: ["#c2410c", "#fde68a"], rank: "Spice Strategist", difficulty: "hard", style: "Heat, curry, layered aromatics", base: "ricebowl", method: "fry", plate: "fusion", likes: ["cajun", "curry", "hotsauce", "ginger", "chili"], signature: "Storm Rice Bowl", lore: "Builds dishes like a weather front. The flavor hits before the plate lands.", x: 77, y: 62 },
      { id: "chef_velvet", name: "Chef Velvet Noir", region: "Paris Night Kitchen", emoji: "🖤", hat: "🎩", colors: ["#111827", "#f97316"], rank: "Plating Icon", difficulty: "hard", style: "Fine dining, sauces, texture contrast", base: "steak", method: "braise", plate: "fine", likes: ["truffle", "butter", "mushroom", "cream"], signature: "Velvet Plate", lore: "A judge magnet. If the plate looks messy, she calls it before tasting.", x: 24, y: 20 },
      { id: "chef_forge", name: "Chef Forge", region: "Chicago Iron Kitchen", emoji: "🍳", hat: "🧢", colors: ["#1f2937", "#f59e0b"], rank: "Line Boss", difficulty: "hard", style: "Fire, speed, service pressure", base: "chicken", method: "grill", plate: "street", likes: ["bbq", "paprika", "bacon", "potato", "pepper"], signature: "Iron Chicken Stack", lore: "Everything is loud, fast, and hot. He never lets a cook settle.", x: 42, y: 18 },
      { id: "chef_orchid", name: "Chef Orchid", region: "Seoul Neon Market", emoji: "🌸", hat: "💮", colors: ["#7c3aed", "#fb7185"], rank: "Flavor Architect", difficulty: "hard", style: "Sweet heat, umami, shine", base: "tofu", method: "saute", plate: "fusion", likes: ["soy", "ginger", "teriyaki", "cajun", "broccoli"], signature: "Neon Tofu Crown", lore: "Turns clean ingredients into something flashy without losing balance.", x: 61, y: 80 },
      { id: "chef_tide", name: "Chef Tide", region: "Sydney Harbour Line", emoji: "🌊", hat: "🧢", colors: ["#0f766e", "#38bdf8"], rank: "Seafood Champion", difficulty: "easy", style: "Seafood, citrus, clean finish", base: "fish", method: "steam", plate: "fine", likes: ["lemon", "shrimp", "salmon", "cilantro"], signature: "Harbor Catch", lore: "A calm cook with one of the sharpest flavor instincts on the circuit.", x: 84, y: 32 }
    ]
  };

  const createChefState = (name, method, plate, base, temp = 375, time = 18, amount = 3) => ({
    name,
    picks: [],
    method,
    plate,
    temp,
    time,
    amount,
    commands: []
  });

  const createState = () => ({
    mode: "quick",
    difficulty: "normal",
    budgetMode: "standard",
    pantryStyle: "full",
    coachMode: "guided",
    speed: "normal",
    activeCategory: "all",
    buildPlayer: "p1",
    maxExtras: 5,
    budget: 16,
    base: DATA.BASES[0],
    openKitchen: false,
    openKitchenRecipe: null,
    openKitchenPersistedAt: null,
    openKitchenResult: null,
    openKitchenJudgeTest: null,
    p1: createChefState("Chef Nova", "saute", "street", "chicken"),
    p2: createChefState("Chef Blaze", "grill", "fine", "steak"),
    actionBonuses: { p1: { flavor: 0, technique: 0, creativity: 0, presentation: 0 }, p2: { flavor: 0, technique: 0, creativity: 0, presentation: 0 } },
    actionLog: { p1: [], p2: [] },
    events: { p1: [], p2: [] },
    career: false,
    careerBoss: null,
    pendingBoss: null,
    winner: null,
    turn: 1
  });

  window.ChefClash = window.ChefClash || {};
  window.ChefClash.data = DATA;
  window.ChefClash.createState = createState;
  window.ChefClash.createChefState = createChefState;
})();
